# Generated by Django 4.2.19 on 2025-03-30 17:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discussion',
            options={'verbose_name': 'diskusia', 'verbose_name_plural': 'diskusie'},
        ),
        migrations.AlterModelOptions(
            name='forum',
            options={'verbose_name': 'diskusné fórum', 'verbose_name_plural': 'diskusné fóra'},
        ),
        migrations.AlterField(
            model_name='discussion',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='autor'),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='čas vytvorenia'),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='discuss',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='diskusia'),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files/', verbose_name='súbor'),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='forum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='forum.forum', verbose_name='fórum'),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='link',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='odkaz'),
        ),
        migrations.AlterField(
            model_name='forum',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='autor'),
        ),
        migrations.AlterField(
            model_name='forum',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='čas vytvorenia'),
        ),
        migrations.AlterField(
            model_name='forum',
            name='description',
            field=models.CharField(blank=True, max_length=1000, verbose_name='popis'),
        ),
        migrations.AlterField(
            model_name='forum',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files/', verbose_name='súbor'),
        ),
        migrations.AlterField(
            model_name='forum',
            name='link',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='odkaz'),
        ),
        migrations.AlterField(
            model_name='forum',
            name='topic',
            field=models.CharField(max_length=300, verbose_name='téma'),
        ),
    ]
