# Generated by Django 4.2.19 on 2025-02-14 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discussion',
            options={'verbose_name': 'Diskusia', 'verbose_name_plural': 'Diskusie'},
        ),
        migrations.AlterModelOptions(
            name='forum',
            options={'verbose_name': 'Diskusné fórum', 'verbose_name_plural': 'Diskusné fóra'},
        ),
    ]
