# Generated by Django 4.2.19 on 2025-03-30 17:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'správa', 'verbose_name_plural': 'správy'},
        ),
        migrations.AlterModelOptions(
            name='privateconversation',
            options={'verbose_name': 'súkromná konverzácia', 'verbose_name_plural': 'súkromné konverzácie'},
        ),
        migrations.AlterModelOptions(
            name='privatemessage',
            options={'verbose_name': 'súkromná správa', 'verbose_name_plural': 'súkromné správy'},
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='obsah'),
        ),
        migrations.AlterField(
            model_name='message',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files/', verbose_name='súbor'),
        ),
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='čas'),
        ),
        migrations.AlterField(
            model_name='message',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL, verbose_name='používateľ'),
        ),
        migrations.AlterField(
            model_name='privateconversation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='čas vytvorenia'),
        ),
        migrations.AlterField(
            model_name='privateconversation',
            name='user1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations_as_user1', to=settings.AUTH_USER_MODEL, verbose_name='používateľ 1'),
        ),
        migrations.AlterField(
            model_name='privateconversation',
            name='user2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations_as_user2', to=settings.AUTH_USER_MODEL, verbose_name='používateľ 2'),
        ),
        migrations.AlterField(
            model_name='privatemessage',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='obsah'),
        ),
        migrations.AlterField(
            model_name='privatemessage',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.privateconversation', verbose_name='konverzácia'),
        ),
        migrations.AlterField(
            model_name='privatemessage',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files/', verbose_name='súbor'),
        ),
        migrations.AlterField(
            model_name='privatemessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='odosielateľ'),
        ),
        migrations.AlterField(
            model_name='privatemessage',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='čas'),
        ),
    ]
