# Generated by Django 4.2.19 on 2025-03-22 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('start_time', models.DateTimeField(db_index=True)),
                ('end_time', models.DateTimeField(db_index=True)),
                ('color', models.CharField(choices=[('#FF0000', 'Dôležité'), ('#00FF00', 'Pripomienky'), ('#0000FF', 'Porady')], default='#FF0000', max_length=7)),
                ('is_global', models.BooleanField(default=False)),
                ('notification_sent_today', models.BooleanField(default=False)),
                ('notification_sent_now', models.BooleanField(default=False)),
                ('notification_sent_created', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
