# Generated by Django 5.1.1 on 2025-01-18 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='notification_sent_today',
            field=models.BooleanField(default=False),
        ),
    ]
