# Generated by Django 4.2.19 on 2025-03-23 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='notification_sent_5_min',
            field=models.BooleanField(default=False),
        ),
    ]
