# Generated by Django 4.2.19 on 2025-03-30 17:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cal', '0002_event_notification_sent_5_min'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'udalosť', 'verbose_name_plural': 'udalosti'},
        ),
        migrations.AlterField(
            model_name='event',
            name='color',
            field=models.CharField(choices=[('#FF0000', 'Dôležité'), ('#00FF00', 'Pripomienky'), ('#0000FF', 'Porady')], default='#FF0000', max_length=7, verbose_name='farba'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(verbose_name='popis'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.DateTimeField(db_index=True, verbose_name='koniec'),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_global',
            field=models.BooleanField(default=False, verbose_name='globálna udalosť'),
        ),
        migrations.AlterField(
            model_name='event',
            name='notification_sent_5_min',
            field=models.BooleanField(default=False, verbose_name='notifikácia 5 minút'),
        ),
        migrations.AlterField(
            model_name='event',
            name='notification_sent_created',
            field=models.BooleanField(default=False, verbose_name='notifikácia vytvorená'),
        ),
        migrations.AlterField(
            model_name='event',
            name='notification_sent_now',
            field=models.BooleanField(default=False, verbose_name='notifikácia teraz'),
        ),
        migrations.AlterField(
            model_name='event',
            name='notification_sent_today',
            field=models.BooleanField(default=False, verbose_name='notifikácia dnes'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(db_index=True, verbose_name='začiatok'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=200, verbose_name='názov'),
        ),
        migrations.AlterField(
            model_name='event',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='používateľ'),
        ),
    ]
