# Generated by Django 5.1.1 on 2025-01-26 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0002_event_notification_sent_today'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='color',
            field=models.CharField(choices=[('#FF0000', 'Červená'), ('#00FF00', 'Zelená'), ('#0000FF', 'Modrá')], default='#FF0000', max_length=7),
        ),
    ]
