# Generated by Django 4.2.19 on 2025-02-21 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0004_alter_event_end_time_alter_event_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='color',
            field=models.CharField(choices=[('#FF0000', 'Dôležité'), ('#00FF00', 'Pripomienky'), ('#0000FF', 'Porady')], default='#FF0000', max_length=7),
        ),
    ]
