# Generated by Django 4.2.19 on 2025-02-21 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0005_alter_event_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='notification_sent_five_minutes',
            field=models.BooleanField(default=False),
        ),
    ]
