# Generated by Django 4.2.19 on 2025-03-30 17:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'verbose_name': 'možnosť', 'verbose_name_plural': 'možnosti'},
        ),
        migrations.AlterModelOptions(
            name='poll',
            options={'verbose_name': 'hlasovanie', 'verbose_name_plural': 'hlasovania'},
        ),
        migrations.AlterModelOptions(
            name='vote',
            options={'verbose_name': 'hlas', 'verbose_name_plural': 'hlasy'},
        ),
        migrations.AlterField(
            model_name='choice',
            name='name',
            field=models.CharField(max_length=20, verbose_name='názov'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='choices',
            field=models.ManyToManyField(blank=True, related_name='related_polls', to='polls.choice', verbose_name='možnosti'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_polls', to=settings.AUTH_USER_MODEL, verbose_name='vytvoril'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='description',
            field=models.TextField(verbose_name='popis'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='end_date',
            field=models.DateTimeField(verbose_name='koniec hlasovania'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='name',
            field=models.CharField(max_length=50, verbose_name='názov'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='notified_closed',
            field=models.BooleanField(default=False, verbose_name='notifikácia uzavretá'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='čas vytvorenia'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='votes', to='polls.choice', verbose_name='možnosť'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='poll',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='votes', to='polls.poll', verbose_name='hlasovanie'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='čas'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='používateľ'),
        ),
    ]
