# Generated by Django 4.2.19 on 2025-03-31 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_choice_options_alter_poll_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poll',
            options={'verbose_name': 'Anketa', 'verbose_name_plural': 'Ankety'},
        ),
    ]
