# Generated by Django 4.2.19 on 2025-03-04 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_poll_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='notified_closed',
            field=models.BooleanField(default=False),
        ),
    ]
