# Generated by Django 4.2.19 on 2025-03-30 17:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sentemail',
            options={'verbose_name': 'odoslaný email', 'verbose_name_plural': 'odoslané emaily'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'profil používateľa', 'verbose_name_plural': 'profily používateľov'},
        ),
        migrations.AlterField(
            model_name='sentemail',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files/', verbose_name='súbor'),
        ),
        migrations.AlterField(
            model_name='sentemail',
            name='message',
            field=models.TextField(verbose_name='správa'),
        ),
        migrations.AlterField(
            model_name='sentemail',
            name='recipient',
            field=models.EmailField(max_length=254, verbose_name='príjemca'),
        ),
        migrations.AlterField(
            model_name='sentemail',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_emails', to=settings.AUTH_USER_MODEL, verbose_name='odosielateľ'),
        ),
        migrations.AlterField(
            model_name='sentemail',
            name='subject',
            field=models.CharField(max_length=255, verbose_name='predmet'),
        ),
        migrations.AlterField(
            model_name='sentemail',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='čas odoslania'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='používateľ'),
        ),
    ]
