# Generated by Django 5.1.1 on 2025-01-08 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentemail',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
    ]
