# Generated by Django 5.1.1 on 2025-01-26 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0004_sentemail_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
    ]
