name: Database Backup

on:
  schedule:
    - cron: "0 3 * * *"  # Spustí sa každý deň o 03:00 UTC
  workflow_dispatch:  # Možnosť manuálneho spustenia

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Nastavenie prostredia
      run: |
        sudo apt update
        sudo apt install -y postgresql-client

    - name: Spustenie backup.sh
      env:
        DB_NAME: ${{ secrets.DB_NAME }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_HOST: ${{ secrets.DB_HOST }}
        MEGA_USER: ${{ secrets.MEGA_USER }}
        MEGA_PASS: ${{ secrets.MEGA_PASS }}
      run: bash backup.sh
