name: Backup PostgreSQL to MEGA

on:
  workflow_dispatch:  # Manuálne spustenie
  schedule:
    - cron: "0 0 * * *"  # Spustenie každý deň o polnoci UTC

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install PostgreSQL client
        run: sudo apt-get install -y postgresql-client

      - name: Dump PostgreSQL database
        env:
          PGPASSWORD: ${{ secrets.DB_PASSWORD }}
        run: |
          pg_dump -h ${{ secrets.DB_HOST }} -U ${{ secrets.DB_USER }} -d ${{ secrets.DB_NAME }} -F c -f backup.dump

      - name: Install MEGA CMD
        run: |
          sudo apt-get update
          sudo apt-get install -y megatools

      - name: Login to MEGA
        run: mega-login ${{ secrets.MEGA_EMAIL }} ${{ secrets.MEGA_PASSWORD }}

      - name: Upload backup to MEGA
        run: mega-put backup.dump /backups/

      - name: Logout from MEGA
        run: mega-logout
